#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): A pallet (package) manager"
	echo
	echo "Usage: $(basename ${0}) import|path|run <warehouse> <pallet> <version>"
	echo -e "\tcommands:"
	echo -e "\t\tversion:           Print the version number for this install of forklift"
	echo -e "\t\timport:            Import the specific pallet to a local warehouse for consumption"
	echo -e "\t\tpath:              Get the path of the specified pallet in the local warehouse"
	echo -e "\t\trun <...> command: Run the specified command in the pallet"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/builtin/common/source

args_min 1
COMMAND="${1}"

case ${COMMAND} in
	-h|--help|help)
	help
	exit 0
	;;
	-v|--version|version)
	VERSION=$(basename ${SELF_DIR})
	if [ "${VERSION}" == "forklift" ]; then
		fail "Could not determine version, this may be a development directory!"
	fi
	echo ${VERSION}
	;;
	*)
	;;
esac

args_min 4
WAREHOUSE="${2}"
PALLET="${3}"
VERSION="${4}"
shift 4

JACK="${SELF_DIR}/builtin/jack/$(${SELF_DIR}/builtin/common/pallet2jack ${WAREHOUSE} ${PALLET} ${VERSION})/jack"
${JACK} ${COMMAND} ${WAREHOUSE} ${PALLET} ${VERSION} $@
