#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install packages on Cygwin"
	echo
	echo "Usage: $(basename ${0}) <package>*"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../common/source

# Note that there can be more than one package to install...
args_min 1

PACKAGES_CYGWIN=()
for ARG in "$@"; do
	SPECIALSCRIPT="${SELF_DIR}/special/${ARG}"
    if [[ -x "${SPECIALSCRIPT}" ]]; then
    	${SPECIALSCRIPT}
    else
    	PACKAGES_CYGWIN+=("${ARG}")
    fi
done

if [ ${#PACKAGES_CYGWIN[@]} -ne 0 ]; then
	EXECUTABLE_NAME="setup-$(${SELF_DIR}/../../common/osinfo -a).exe"
	EXECUTABLE_FILE="${SELF_DIR}/${EXECUTABLE_NAME}"
	if [ ! -f ${EXECUTABLE_FILE} ]; then
		echo -e "${CFMT_INFO}Downloading cygwin installer ${CFMT_NORMAL}" >&2
		curl https://cygwin.com/${EXECUTABLE_NAME} -o ${EXECUTABLE_FILE}
		chmod +x ${EXECUTABLE_FILE}
	fi
	echo -e "${CFMT_INFO}Intalling ${PACKAGES_CYGWIN[@]} using cygwin installer ${CFMT_NORMAL}" >&2
	sleep 2
	echo ${EXECUTABLE_FILE} -q -W -P ${PACKAGES_CYGWIN[@]}
fi

echo -e "${CFMT_SUCCESS}Intalled ${@}${CFMT_NORMAL}" >&2
