#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install Eclipse on windows"
	echo
	echo "Usage: $(basename ${0})"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source.bash

. "${SELF_DIR}/../install-common"
install java java

SP_NAME="Eclipse"
SP_TARGET="/cygdrive/c/Program Files/eclipse"
SP_RELATIVE=""

URL_ECLIPSE="https://www.eclipse.org"

# Accepts the temporary directory as an argument, returns the version number for the most recent version we can download on stdout
function sp_downloadversion() {
	curl -L "${URL_ECLIPSE}/downloads/" 2>/dev/null | grep -F 'Get <strong>Eclipse IDE ' | sed -e 's/.*Eclipse IDE \([^<]*\).*/\1/' -e 's/&#8209;/-/'
}
# Fails if the program is not installed, otherwise returns install directory and installed version as two lines on stdout
function sp_installedversion() {
	if WHICH_OUTPUT=$(which eclipse 2> /dev/null); then
		ECLIPSEDIR="$(dirname "${WHICH_OUTPUT}")"
		echo "${ECLIPSEDIR}"
	 	cat "$(find "${ECLIPSEDIR}" -name about.mappings | grep -F 'org.eclipse.platform')" | grep '^1=' | sed -e 's/1=//'
	else
		exit 1
	fi
}
# Accepts the temporary directory as an argument, downloads the most recent version, and creates the directory structure that should be installed. Returns the absolute path to that directory on stdout
function sp_downloadsource() {
	pushd "${1}" > /dev/null 2>&1
		URL_DOWNLOADS="${URL_ECLIPSE}$(curl -L "${URL_ECLIPSE}/downloads/" 2>/dev/null | grep -F '>Download Packages</a>' | cut -f1 -d'|' | sed -e 's/.*href="\([^"]*\)".*/\1/')"
		URL_PACKAGE="${URL_ECLIPSE}$(curl -L "${URL_DOWNLOADS}" 2>/dev/null | grep -F '>Eclipse IDE for Java Developers</a>' | sed -e 's/.*href="\([^"]*\)".*/\1/')"
		URL_DOWNLOAD="https:$(curl -L "${URL_PACKAGE}" 2>/dev/null | grep -F "windows-64bit" -A 1 | grep -F '>x86_64</a>' | sed -e 's/.*href="\([^"]*\)".*/\1/')"
		URL_MIRROR="${URL_ECLIPSE}/downloads/$(curl -L "${URL_DOWNLOAD}" 2> /dev/null | grep -F '>File:<' | sed -e 's/<\/a>.*//' | sed -e 's/.*href="\([^"]*\)".*/\1/')"
		URL_ACTUAL="$(curl -L "${URL_MIRROR}" 2> /dev/null | grep -F 'click here' | sed -e 's/.*href="\([^"]*\)".*/\1/')"
		
		FILENAME="$(basename "${URL_ACTUAL}")"
		curl -L "${URL_ACTUAL}" -o "${FILENAME}"
		unzip "${FILENAME}" > /dev/null 2>&1
	popd > /dev/null 2>&1
	find "${1}" -maxdepth 1 -type d -name "eclipse*"
}

. ${SELF_DIR}/../special-common
