#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install maven on windows"
	echo
	echo "Usage: $(basename ${0})"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source

if which mvn > /dev/null 2>&1; then
	echo -e "${CFMT_INFO}Maven is already installed${CFMT_NORMAL}" >&2
	exit 0
fi

MVN_TEMPDIR=$(mktemp -d)
trap "{ rm -rf ${MVN_TEMPDIR}; }" EXIT
echo -e "${CFMT_INFO}Installing maven${CFMT_NORMAL} (temp dir is ${MVN_TEMPDIR})" >&2

echo -e "${CFMT_INFO}Getting download link${CFMT_NORMAL}" >&2
curl -o ${MVN_TEMPDIR}/download.cgi https://maven.apache.org/download.cgi
MVN_URL=$(grep -E "/apache-maven-([^-]*)-bin.tar.gz\">apache-maven-\\1-bin.tar.gz</a>" ${MVN_TEMPDIR}/download.cgi | sed -e 's#.*href="\([^"]*\)".*#\1#')

echo -e "${CFMT_INFO}Downloading Maven from ${MVN_URL}${CFMT_NORMAL}" >&2
curl -o ${MVN_TEMPDIR}/maven.tar.gz ${MVN_URL}

echo -e "${CFMT_INFO}Untaring maven${CFMT_NORMAL}" >&2
pushd ${MVN_TEMPDIR} > /dev/null 2>&1
	tar -xf maven.tar.gz
popd > /dev/null 2>&1
SOURCE=$(find ${MVN_TEMPDIR} -maxdepth 1 -type d -name "apache-maven-*")

TARGET="/cygdrive/c/Program Files/Maven"
echo -e "${CFMT_INFO}Installing Maven to $(cygpath -w "${TARGET}")${CFMT_NORMAL} (and adding to windows path)" >&2
cat > ${MVN_TEMPDIR}/setpath.ps1 <<EOF
\$ErrorActionPreference = "Stop"
\$target = '$(cygpath -w "${TARGET}")'
echo "Moving maven to \$target"
Move-Item '$(cygpath -w "${SOURCE}")' "\$target"

echo "Adding \$target to the path"
\$currentPath = [Environment]::GetEnvironmentVariable('path', 'machine');
[Environment]::SetEnvironmentVariable('path', "\$(\$currentPath);\$(\$target)\\bin",'Machine');
echo "Success"
pause
EOF
powershell -NoProfile -ExecutionPolicy Bypass -Command "\$p = Start-Process powershell \"-Command $(cygpath -w ${MVN_TEMPDIR}/setpath.ps1)\" -Verb runAs -PassThru -Wait; Exit \$p.ExitCode"

echo -e "${CFMT_SUCCESS}Successfully installed maven${CFMT_NORMAL}!" >&2
