#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install maven on windows"
	echo
	echo "Usage: $(basename ${0})"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source.bash

. "${SELF_DIR}/../install-common"
install java java

SP_NAME="maven"
SP_TARGET="/cygdrive/c/Program Files/Maven"
SP_RELATIVE="bin"

# Accepts the temporary directory as an argument, returns the version number for the most recent version we can download on stdout
function sp_downloadversion() {
	URL=$(curl https://maven.apache.org/download.cgi 2> /dev/null | grep -E "/apache-maven-([^-]*)-bin.tar.gz\">apache-maven-\\1-bin.tar.gz</a>" | sed -e 's#.*href="\([^"]*\)".*#\1#')
	echo "${URL}" > "${1}/url"
	basename "${URL}" | cut -f3 -d '-'
}
# Fails if the program is not installed, otherwise returns install directory and installed version as two lines on stdout
function sp_installedversion() {
	if WHICH_OUTPUT=$(which mvn 2> /dev/null); then
		dirname "$(dirname "${WHICH_OUTPUT}")"
		mvn --version | head -n1 | cut -f3 -d ' '
	else
		exit 1
	fi
}
# Accepts the temporary directory as an argument, downloads the most recent version, and creates the directory structure that should be installed. Returns the absolute path to that directory on stdout
function sp_downloadsource() {
	pushd "${1}" > /dev/null 2>&1
		curl -o "maven.tar.gz" $(cat "url")
		tar -xf maven.tar.gz
	popd > /dev/null 2>&1
	find "${1}" -maxdepth 1 -type d -name "apache-maven-*"
}

. ${SELF_DIR}/../special-common
