#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install SmartGit on windows"
	echo
	echo "Usage: $(basename ${0}) (<version>)"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source.bash

args_max 1

SMARTGIT_APPROX=$(curl -L "https://www.syntevo.com/smartgit/download/" 2> /dev/null | grep "Download SmartGit" | sed -e 's/.*Download SmartGit \([0-9.]*\).*/\1/')
SMARTGIT_LATEST=$(curl -L "https://www.syntevo.com/smartgit/download/" 2> /dev/null | grep "Version ${SMARTGIT_APPROX}"| sed -e 's/.*Version \([0-9.]*\).*/\1/')
echo -e "${CFMT_INFO}Latest SmartGit is ${SMARTGIT_LATEST}${CFMT_NORMAL}" >&2

if [[ $# -eq 1 ]]; then
	case "${1}" in
		-h|--help|help)
		help
		exit 0
		;;
		*)
		SMARTGIT_VERSION="${1}"
		;;
	esac
else
	SMARTGIT_VERSION="${SMARTGIT_LATEST}"
fi

SMARTGIT_INSTALLEDDIRS=("/cygdrive/c/Program Files (x86)/SmartGit" "/cygdrive/c/Program Files/SmartGit")
for SMARTGIT_INSTALLEDDIR in "${SMARTGIT_INSTALLEDDIRS[@]}"; do
	if [ -d "${SMARTGIT_INSTALLEDDIR}" ]; then
		echo -e "${CFMT_INFO}SmartGit is already installed${CFMT_NORMAL}" >&2
		exit 0
	fi
done

. "${SELF_DIR}/../install-common"
install unzip unzip

SMARTGIT_MAJOR=$(echo "${SMARTGIT_VERSION}" | sed -e 's/\..*//')
SMARTGIT_MAJORLATEST=$(echo "${SMARTGIT_LATEST}" | sed -e 's/\..*//')
if [[ ${SMARTGIT_MAJOR} -ge ${SMARTGIT_MAJORLATEST} ]]; then
	SMARTGIT_URL_PREFIX="https://www.syntevo.com/downloads/smartgit/"
else
	SMARTGIT_URL_PREFIX="https://www.syntevo.com/downloads/smartgit/archive/"
fi
if [[ ${SMARTGIT_MAJOR} -ge 18 ]]; then
	SMARTGIT_URL_FILENAME="smartgit-win-$(echo "${SMARTGIT_VERSION}" | sed -e 's/\./_/g').zip"
else
	SMARTGIT_URL_FILENAME="smartgit-win32-setup-jre-$(echo "${SMARTGIT_VERSION}" | sed -e 's/\./_/g').zip"
fi
SMARTGIT_URL="${SMARTGIT_URL_PREFIX}/${SMARTGIT_URL_FILENAME}"

INSTALL_TEMPDIR=$(mktemp -d)
trap "{ rm -rf ${INSTALL_TEMPDIR}; }" EXIT
echo -e "${CFMT_INFO}Downloading SmartGit ${SMARTGIT_VERSION}${CFMT_NORMAL} (temp dir is ${INSTALL_TEMPDIR})" >&2

pushd "${INSTALL_TEMPDIR}" > /dev/null 2>&1
	curl -L -o "smartgit.zip" "${SMARTGIT_URL}"
	unzip "smartgit.zip"
	SMARTGIT_INSTALLER=$(find . -name "*.exe")
	chmod +x "${SMARTGIT_INSTALLER}"
	"${SMARTGIT_INSTALLER}" /SP- /SILENT
popd > /dev/null 2>&1

echo -e "${CFMT_SUCCESS}Successfully installed SmartGit${CFMT_NORMAL}!" >&2
