#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install SmartSync on windows"
	echo
	echo "Usage: $(basename ${0}) (<version>)"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source.bash

args_max 1

SMARTSYNC_APPROX=$(curl -L "https://www.syntevo.com/smartsynchronize/download/" 2> /dev/null | grep "Download SmartSync" | sed -e 's/.*Download SmartSynchronize \([0-9.]*\).*/\1/')
SMARTSYNC_LATEST=$(curl -L "https://www.syntevo.com/smartsynchronize/download/" 2> /dev/null | grep "Version ${SMARTSYNC_APPROX}"| sed -e 's/.*Version \([0-9.]*\).*/\1/')
echo -e "${CFMT_INFO}Latest SmartSync is ${SMARTSYNC_LATEST}${CFMT_NORMAL}" >&2

if [[ $# -eq 1 ]]; then
	case "${1}" in
		-h|--help|help)
		help
		exit 0
		;;
		*)
		SMARTSYNC_VERSION="${1}"
		;;
	esac
else
	SMARTSYNC_VERSION="${SMARTSYNC_LATEST}"
fi

SMARTSYNC_INSTALLEDDIRS=("/cygdrive/c/Program Files (x86)/SmartSynchronize" "/cygdrive/c/Program Files/SmartSynchronize")
for SMARTSYNC_INSTALLEDDIR in "${SMARTSYNC_INSTALLEDDIRS[@]}"; do
	if [ -d "${SMARTSYNC_INSTALLEDDIR}" ]; then
		echo -e "${CFMT_INFO}SmartSync is already installed${CFMT_NORMAL}" >&2
		exit 0
	fi
done

. "${SELF_DIR}/../install-common"
install unzip unzip

SMARTSYNC_MAJOR=$(echo "${SMARTSYNC_VERSION}" | sed -e 's/\..*//')
SMARTSYNC_MAJORLATEST=$(echo "${SMARTSYNC_LATEST}" | sed -e 's/\..*//')
if [[ ${SMARTSYNC_MAJOR} -ge ${SMARTSYNC_MAJORLATEST} ]]; then
	SMARTSYNC_URL_PREFIX="https://www.syntevo.com/downloads/smartsynchronize/"
else
	SMARTSYNC_URL_PREFIX="https://www.syntevo.com/downloads/smartsynchronize/archive/"
fi
if [[ ${SMARTSYNC_MAJOR} -ge 18 ]]; then
	SMARTSYNC_URL_FILENAME="smartsynchronize-win-$(echo "${SMARTSYNC_VERSION}" | sed -e 's/\./_/g').zip"
else
	SMARTSYNC_URL_FILENAME="smartsynchronize-win32-setup-jre-$(echo "${SMARTSYNC_VERSION}" | sed -e 's/\./_/g').zip"
fi
SMARTSYNC_URL="${SMARTSYNC_URL_PREFIX}/${SMARTSYNC_URL_FILENAME}"

INSTALL_TEMPDIR=$(mktemp -d)
trap "{ rm -rf ${INSTALL_TEMPDIR}; }" EXIT
echo -e "${CFMT_INFO}Downloading SmartSync ${SMARTSYNC_VERSION}${CFMT_NORMAL} (temp dir is ${INSTALL_TEMPDIR})" >&2

pushd "${INSTALL_TEMPDIR}" > /dev/null 2>&1
	curl -L -o "smartsync.zip" "${SMARTSYNC_URL}"
	unzip "smartsync.zip"
	SMARTSYNC_INSTALLER=$(find . -name "*.exe")
	chmod +x "${SMARTSYNC_INSTALLER}"
	"${SMARTSYNC_INSTALLER}" /SP- /SILENT
popd > /dev/null 2>&1

echo -e "${CFMT_SUCCESS}Successfully installed SmartSync${CFMT_NORMAL}!" >&2
