#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install SmartSVN on windows"
	echo
	echo "Usage: $(basename ${0}) (<version>)"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../../common/source.bash

args_max 1

SMARTSVN_LATEST=$(curl -L "https://www.smartsvn.com/download/" 2> /dev/null | grep "Download SmartSVN" | sed -e 's/.*Download SmartSVN \([0-9.]*\).*/\1/')
echo -e "${CFMT_INFO}Latest SmartSVN is ${SMARTSVN_LATEST}${CFMT_NORMAL}" >&2

if [[ $# -eq 1 ]]; then
	case "${1}" in
		-h|--help|help)
		help
		exit 0
		;;
		*)
		SMARTSVN_VERSION="${1}"
		;;
	esac
else
	SMARTSVN_VERSION="${SMARTSVN_LATEST}"
fi

SMARTSVN_INSTALLEDDIR="/cygdrive/c/Program Files (x86)/SmartSVN"
if [ -d "${SMARTSVN_INSTALLEDDIR}" ]; then
	echo -e "${CFMT_INFO}SmartSVN is already installed${CFMT_NORMAL}" >&2
	exit 0
fi

. "${SELF_DIR}/../install-common"
install unzip unzip

SMARTSVN_MAJOR=$(echo "${SMARTSVN_VERSION}" | sed -e 's/\..*//')
SMARTSVN_MAJORLATEST=$(echo "${SMARTSVN_LATEST}" | sed -e 's/\..*//')
if [[ ${SMARTSVN_MAJOR} -ge ${SMARTSVN_MAJORLATEST} ]]; then
	SMARTSVN_URL_PREFIX="https://www.smartsvn.com/downloads/smartsvn/"
else
	SMARTSVN_URL_PREFIX="https://www.smartsvn.com/downloads/smartsvn/archive/"
fi
SMARTSVN_URL="${SMARTSVN_URL_PREFIX}/smartsvn-windows-setup-$(echo "${SMARTSVN_VERSION}" | sed -e 's/\./_/g').zip"

INSTALL_TEMPDIR=$(mktemp -d)
trap "{ rm -rf ${INSTALL_TEMPDIR}; }" EXIT
echo -e "${CFMT_INFO}Downloading SmartSVN ${SMARTSVN_VERSION}${CFMT_NORMAL} (temp dir is ${INSTALL_TEMPDIR})" >&2

pushd "${INSTALL_TEMPDIR}" > /dev/null 2>&1
	curl -L -o "smartsvn.zip" "${SMARTSVN_URL}"
	unzip "smartsvn.zip"
	SMARTSVN_INSTALLER=$(find . -name "*.exe")
	chmod +x "${SMARTSVN_INSTALLER}"
	"${SMARTSVN_INSTALLER}" /SP- /SILENT
popd > /dev/null 2>&1

echo -e "${CFMT_SUCCESS}Successfully installed SmartSVN${CFMT_NORMAL}!" >&2
