#!/bin/bash
set -eu -o pipefail

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

echo "Installing forklift test pallet"
ln -svfT $(cd ${SELF_DIR}/.. && pwd -P)/forklift-test ${FLBIN_DIR}/forklift-test
