#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Uninstall this instance of forklift"
	echo
	echo "Usage: $(basename ${0})"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. $(cd $(dirname ${FORKLIFT}) && pwd -P)/builtin/common/source.bash

DELETER=$(mktemp)
cat > ${DELETER} <<EOF
#!/bin/bash
set -eu -o pipefail

echo "Deleting forklift cache"
sleep 1s
rm -rf ${FLCACHE_ROOT}

echo "Removing forklift from path"
TEMP_PROFILE=\$(mktemp)
grep -vF "forklift" ~/.bash_profile || true > \${TEMP_PROFILE}
mv \${TEMP_PROFILE} ~/.bash_profile

echo -e "${CFMT_SUCCESS}Success${CFMT_NORMAL}!"
rm -rf ${DELETER}
EOF
chmod +x ${DELETER}
echo -e "Forking delete script to ensure complete deletion"
${DELETER} &
