#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Install packages on RHEL"
	echo
	echo "Usage: $(basename ${0}) <package>*"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../common/source.bash

# Note that there can be more than one package to install...
args_min 1

echo -e "${CFMT_INFO}Intalling ${@} using yum ${CFMT_NORMAL}" >&2
sleep 1

sudo yum -y install ${@} 	

echo -e "${CFMT_SUCCESS}Intalled ${@}${CFMT_NORMAL}" >&2
