#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Run the specified command, or print it's cached results"
	echo
	echo "Usage: $(basename ${0}) <command...>"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/source

set +u
if [ -z ${CACHE_ROOT+x} ]; then
	CACHE_ROOT=${FLCACHE_ROOT}/cache
fi
set -u

if [ ! -d ${CACHE_ROOT} ]; then
	mkdir -p ${CACHE_ROOT}
	cat >${CACHE_ROOT}/README.md << EOF
# Cache

This directory contains the cached results of running various long-running commands.
Each subdirectory is named by the SHA1 sum of the commands working directory, command and arguments.
Within each subdirectory you will find the following:

* \`cmd\` which contains the exact command which has been run
* \`exitcode\` which contains the exit code
* \`stdout\` which contains the standard output and error text

For more information please see \`${SELF}\`.
EOF
fi

for ARG in "$@"; do
	CMD=( "${CMD[@]}" "$ARG" )
done
SHA1=$(echo -n "$(pwd -P) ${CMD[@]}" | sha1sum | awk '{print $1}')

CMD_DIR=${CACHE_ROOT}/${SHA1}
CMD_STDOUT="${CMD_DIR}/stdout"
CMD_EXITCODE="${CMD_DIR}/exitcode"
CMD_FILE="${CMD_DIR}/cmd"

if [ ! -f "${CMD_EXITCODE}" ]; then
	mkdir -p ${CMD_DIR}
	echo "${CMD[@]}" > ${CMD_FILE}
	"${CMD[@]}" > ${CMD_STDOUT} 2>&1
	echo ${PIPESTATUS[0]} > ${CMD_EXITCODE}
fi

cat ${CMD_STDOUT}
exit $(cat ${CMD_EXITCODE})
