#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Determine the default jack from a warehouse identifire"
	echo
	echo "Usage: $(basename ${0}) <warehouse> <pallet> <jack>"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/source

args_min 1
WAREHOUSE="${1}"

case ${WAREHOUSE} in
	-h|--help)
	help
	exit 0
	;;
esac

args_eq 3
PALLET="${2}"
VERSION="${3}"
shift 3

case ${WAREHOUSE} in
	builtin)
	echo "builtin"
	;;
	com.github)
	echo "github"
	;;
	*)
	fail "Unknown warehouse \"${WAREHOUSE}\""
	;;
esac
