#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Determine the jack from a pallet identifier"
	echo
	echo "Usage: $(basename ${0}) <warehouse> <pallet> <jack>"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/source

args_min 1
WAREHOUSE="${1}"

case ${WAREHOUSE} in
	-h|--help)
	help
	exit 0
	;;
esac

args_eq 3
PALLET="${2}"
VERSION="${3}"
shift 3

case ${WAREHOUSE} in
	builtin)
	echo "builtin"
	;;
	com.github)
	echo "github"
	;;
	org.maven)
	echo "maven"
	;;
	*)
	pushd ${SELF_DIR} > /dev/null 2>&1
		echo -e "${CFMT_INFO}Searching for jacks for pallet ${WAREHOUSE} ${PALLET} ${VERSION}${CFMT_NORMAL}" >&2
		JACKFILE=$(mktemp)
		set +e
		${SELF_DIR}/cache ${SELF_DIR}/findjacks ${WAREHOUSE} ${PALLET} ${VERSION} > ${JACKFILE}
		set -e
		if [ ! -f ${JACKFILE} ]; then
			fail "Could not find suitable jack for pallet (couldn't even search for jacks)"
		fi
		JACKCOUNT=$(wc -l ${JACKFILE} | cut -f 1 -d ' ')
		if [[ ${JACKCOUNT} -ne 1 ]]; then
			fail "Could not find suitable jack for pallet (found ${JACKCOUNT} jacks)"
		fi
		cat ${JACKFILE}
		rm ${JACKFILE}
	popd > /dev/null 2>&1
	;;
esac
