#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Determine the default jack from a warehouse identifire"
	echo
	echo "Usage: $(basename ${0}) <warehouse>"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/consoleformat
. ${SELF_DIR}/util

if [[ $# -lt 1 ]]; then
	fail "Too few arguments, 1 is required!"
fi

WAREHOUSE="${1}"
shift 1

if [[ $# -gt 0 ]]; then
	fail "Too many arguments!"
fi

case ${WAREHOUSE} in
	-h|--help)
	help
	;;
	builtin)
	echo "builtin"
	;;
	*)
	fail "Unknown warehouse \"${WAREHOUSE}\""
	;;
esac
