#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Run the specified command, or print it's cached results"
	echo
	echo "Usage: $(basename ${0}) <command...>"
	echo "\tYou may override the cache root directory by specifying the CACHE_ROOT environment variable"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../common/source.bash

CACHE_ENTRYTEST=0
case ${1} in
	-h|--help|help)
	help
	exit 0
	;;
	-t|--test)
	CACHE_ENTRYTEST=1
	shift 1
	;;
esac

set +u
if [ -z ${CACHE_ROOT+x} ]; then
	set -u
	CACHE_ROOT=${FLCACHE_ROOT}/cache
fi
set -u

if [[ ${CACHE_ENTRYTEST} -ne 1 ]] && [ ! -d ${CACHE_ROOT} ]; then
	mkdir -p ${CACHE_ROOT}
	cat >${CACHE_ROOT}/README.md << EOF
# Cache

This directory contains the cached results of running various long-running commands.
Each subdirectory is named by the SHA1 sum of the commands working directory, command and arguments.
Within each subdirectory you will find the following:

* \`cmd\` which contains the exact command which has been run
* \`exitcode\` which contains the exit code
* \`stdout\` which contains the standard output and error text

For more information please see \`${SELF}\`.
EOF
fi

for ARG in "$@"; do
	CMD=( "${CMD[@]}" "$ARG" )
done
SHA1=$(echo -n "$(pwd -P) ${CMD[@]}" | sha1sum | awk '{print $1}')

CMD_DIR=${CACHE_ROOT}/${SHA1}
CMD_EXITCODE="${CMD_DIR}/exitcode"

if [[ ${CACHE_ENTRYTEST} -eq 1 ]]; then
	if [ -f "${CMD_EXITCODE}" ]; then
		echo "Cache entry exists"
		exit 0 
	else
		echo "Cache entry not found"
		exit 1
	fi
fi

CMD_STDOUT="${CMD_DIR}/stdout"
CMD_STDERR="${CMD_DIR}/stderr"

if [ ! -f "${CMD_EXITCODE}" ]; then
	mkdir -p ${CMD_DIR}
	echo "${CMD[@]}" > "${CMD_DIR}/cmd"
	"${CMD[@]}" > ${CMD_STDOUT} 2> ${CMD_STDERR}
	echo ${PIPESTATUS[0]} > ${CMD_EXITCODE}
fi

cat ${CMD_STDOUT}
cat ${CMD_STDERR} >&2
exit $(cat ${CMD_EXITCODE})
