#!/bin/bash
set -eu -o pipefail

function help () {
	echo "$(basename ${0}): Trivial jack for built-in pallets"
	echo
	echo "Usage: $(basename ${0}) test|import|path|run builtin <pallet> current"
	echo -e "\tcommands:"
	echo -e "\t\ttest:              Test whether this jack can move the specified pallet"
	echo -e "\t\timport:            Import the pallet (nop for the builtin jack)"
	echo -e "\t\tpath:              Get the path of the specified pallet on the local machine"
	echo -e "\t\trun <...> command: Run the specified command in the pallet"
	echo -e "\t\tupdate:            Check for and install updates to the specified pallet (always succeeds for this jack)"
	echo -e "\t\tdelete:            Not supported for builtin pallets"
	echo
}

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

. ${SELF_DIR}/../../common/source.bash

args_min 1
COMMAND="${1}"

case ${COMMAND} in
	-h|--help|help)
	help
	exit 0
esac

args_min 4
WAREHOUSE="${2}"
PALLET="${3}"
VERSION="${4}"
shift 4

if [ "${WAREHOUSE}" != "builtin" ]; then
	fail "Unknown warehouse \"${WAREHOUSE}\", expected \"builtin\""
fi
if [ "${VERSION}" != "current" ]; then
	fail "Unknown version \"${VERSION}\", expected \"current\""
fi

case ${COMMAND} in
	test)
	# Nothing to do here, since there are already tests above
	;;
	import)
	if [[ $# -gt 0 ]]; then
		fail "Too many arguments!"
	fi
	;;
	path)
	if [[ $# -gt 0 ]]; then
		fail "Too many arguments!"
	fi
	echo $(cd ${SELF_DIR}/../../${PALLET} && pwd -P)
	;;
	run)
	COMMAND=$(cd ${SELF_DIR}/../../${PALLET} && pwd -P)/${1}
	shift
	${COMMAND} $@
	;;
	update)
	# Nothing to do here, since builtin pallets are always up to date
	;;
	delete)
	fail "Cannot delete builtin pallets"
	;;
	*)
	fail "Unknown command: ${COMMAND}"
	;;
esac
